//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICPS.Forms
{
    
    #region Windows Form Designer generated code
    public partial class LoginForm
    {
        private void InitializeComponent()
        {
            this.enterButton = new System.Windows.Forms.Button();
            this.loginLabel = new System.Windows.Forms.Label();
            this.loginTextBox = new System.Windows.Forms.TextBox();
            this.passwordLabel = new System.Windows.Forms.Label();
            this.passwordTextBox = new System.Windows.Forms.TextBox();
            // 
            // enterButton
            // 
            this.enterButton.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.enterButton.Text = "Войти";
            this.enterButton.UseVisualStyleBackColor = true;
            this.enterButton.Location = new System.Drawing.Point(8, 88);
            this.enterButton.Name = "enterButton";
            this.enterButton.TabIndex = 0;
            this.enterButton.Click += new System.EventHandler(this.EnterButton_Click);
            // 
            // loginLabel
            // 
            this.loginLabel.Image = null;
            this.loginLabel.Text = "Пароль:";
            this.loginLabel.Location = new System.Drawing.Point(8, 48);
            this.loginLabel.Name = "loginLabel";
            this.loginLabel.TabIndex = 1;
            // 
            // loginTextBox
            // 
            this.loginTextBox.Text = "";
            this.loginTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.loginTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.loginTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.loginTextBox.Location = new System.Drawing.Point(120, 48);
            this.loginTextBox.Name = "loginTextBox";
            this.loginTextBox.Size = new System.Drawing.Size(129, 20);
            this.loginTextBox.TabIndex = 2;
            // 
            // passwordLabel
            // 
            this.passwordLabel.Image = null;
            this.passwordLabel.Text = "Логин:";
            this.passwordLabel.Location = new System.Drawing.Point(8, 16);
            this.passwordLabel.Name = "passwordLabel";
            this.passwordLabel.TabIndex = 1;
            // 
            // passwordTextBox
            // 
            this.passwordTextBox.Text = "Пароль:";
            this.passwordTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.passwordTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.passwordTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTextBox.Location = new System.Drawing.Point(120, 16);
            this.passwordTextBox.Name = "passwordTextBox";
            this.passwordTextBox.Size = new System.Drawing.Size(129, 20);
            this.passwordTextBox.TabIndex = 2;
            // 
            // LoginForm
            // 
            this.ClientSize = new System.Drawing.Size(292, 132);
            this.Text = "Вход";
            this.Controls.Add(this.enterButton);
            this.Controls.Add(this.loginLabel);
            this.Controls.Add(this.loginTextBox);
            this.Controls.Add(this.passwordLabel);
            this.Controls.Add(this.passwordTextBox);
            this.Name = "LoginForm";
        }
        private System.Windows.Forms.Button enterButton;
        private System.Windows.Forms.Label loginLabel;
        private System.Windows.Forms.TextBox loginTextBox;
        private System.Windows.Forms.Label passwordLabel;
        private System.Windows.Forms.TextBox passwordTextBox;
    }
    #endregion
}
